# Generated by Django 5.0.6 on 2024-06-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
