# Generated by Django 5.0.6 on 2024-06-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacliente',
            name='historial_pedido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
