# Generated by Django 5.0.6 on 2024-06-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cuentacliente_historial_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacliente',
            name='historial_pedido',
        ),
        migrations.AddField(
            model_name='cuentacliente',
            name='historial_pedido',
            field=models.ManyToManyField(to='api.pedido'),
        ),
    ]
