# Generated by Django 5.0.6 on 2024-07-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_detallepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacliente',
            name='historial_pedido',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=50),
        ),
    ]
