# Generated by Django 5.0.6 on 2024-07-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pedido_productos_detallepedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
    ]
